include: package:lint/strict.yaml
analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart, lib/**.gr.dart, lib/l10n/generated/*]

linter:
  rules:
    always_specify_types: true
    avoid_classes_with_only_static_members: false
    prefer_single_quotes: true
